server {
    listen 80;
    
    # Catch all traffic. You can replace '_' with your actual domain name later
    server_name _; 

    location /.well-known/acme-challenge/ {
        # Using alias tells Nginx: "Look EXACTLY in this folder"
        alias /var/www/certbot/.well-known/acme-challenge/;
    }

    # 1. Serve Uploaded Images Directly (Extremely Fast)
    location /public/uploads/ {
        alias /app/public/uploads/;
        
        # Tell the browser to cache images for 30 days for better performance
        expires 30d;
        access_log off;
        add_header Cache-Control "public, no-transform";
    }

    # 2. Forward everything else to your Node.js backend
    location / {
        # 'backend' is the exact name of the service in docker-compose.yml
        proxy_pass http://backend:5000;
        
        # Standard proxy headers
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        # Pass the real IP of the user to Node.js
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}